---
title: "Mad Lions - Gráfica de picks"
author: "Tet"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Paquetes utilizados

```{r}
library(tidyverse)
library(googledrive)
library(googlesheets4)
```

## Obtención de datos desde Google Drive

```{r}
drive_auth(oauth_token = "token.rds")
picks_raw <- drive_get(id ="1WAXDVqF0Bm2QvADV76uPd78n03oLLl_NJVFVfItHKHE") %>% 
  read_sheet(range = "drafts!A45:O994") %>%
  mutate(e_sup = as.character(e_sup)) %>% 
  filter(!is.na(fecha))
```

## Limpiando y posicionando la información en el formato deseado

```{r}
picks <- picks_raw %>%
  select(-c(e_top,e_jg,e_mid,e_adc,e_sup)) %>% 
  gather(key = linea, value = campeon, -fecha, -nuestro_lado, -nombre_equipo_e, -resultado, -patch) %>% 
  mutate(nuestro_lado = as_factor(nuestro_lado),
         patch = as_factor(patch),
         resultado = as_factor(resultado),
         linea = as_factor(linea),
         campeon = as_factor(campeon))
```

## Obteniendo porcentajes de victoria por campeon
```{r}
#Intentando obtener  porcentaje de victoria por campeon
porcentajes <- picks %>%
  group_by(linea, campeon) %>%
  mutate(won = case_when(resultado == "WIN" ~ 1),
         lost = case_when(resultado == "LOSE" ~ 1)) %>% 
  summarize(ganados = sum(won, na.rm = TRUE), 
            perdidos = sum(lost, na.rm = TRUE), 
            total = ganados + perdidos,
            win_p = ganados/total, 
            lose_p = perdidos/total) %>% 
  select(linea, campeon, win_p, lose_p)
```

## Mezclanda data sets

```{r}
picks_porcentaje <- left_join(picks, porcentajes, by = c("linea", "campeon"))
```


## Construyendo la gráfica de selecciones del scrim

```{r}
picks_porcentaje %>% ggplot(aes(x = campeon, fill = resultado)) +
  geom_bar(stat = "count", width = 0.5) +
  scale_fill_hue(direction = -1, h.start= 150) +
  facet_wrap(~linea, scales = "free_x", nrow = 1, ncol = 5) +
  theme_bw() +
  theme(legend.position = "right", axis.text.x = element_text(angle = 45, hjust = 0.8)) +
  labs(title = "Campeones practicados en el parche 9.6 en scrims", y = "Cantidad de juegos", x = "Campeones", fill = "Resultado")
```

## Gráfica experimental con porcentajes de victoria (No completado todavía)
```{r}
#grafica
picks_porcentaje %>% ggplot(aes(x = campeon, fill = resultado)) +
  geom_bar(stat = "count", width = 0.5) +
  scale_fill_hue(direction = -1, h.start= 150) +
  facet_wrap(~linea, scales = "free_x", nrow = 1, ncol = 5) +
  theme_bw() +
  theme(legend.position = "right", axis.text.x = element_text(angle = 45, hjust = 0.8)) +
  geom_text(aes(label = paste0(picks_porcentaje$win_p*100,"%"), y = "count"),
            position = position_stack(vjust = 0.5)) +
  labs(title = "Campeones practicados en el parche 9.6 en scrims", y = "Cantidad de juegos", x = "Campeones", fill = "Resultado")
```

